# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nAd7oyBuylMkp7eNjV1E49AZTNq4zbMB
"""



from roboflow import Roboflow
rf = Roboflow(api_key="uABs9vZdE4figY5Vdm8m")
project = rf.workspace("nour-ragab").project("lozy-merged-ov8uw")
version = project.version(1)
dataset = version.download("yolov8")

import os, shutil, random

base = "Lozy-Merged--1"
combined_img = f"{base}/all_images"
combined_lbl = f"{base}/all_labels"
os.makedirs(combined_img, exist_ok=True)
os.makedirs(combined_lbl, exist_ok=True)

for split in ["train", "valid", "test"]:
    img_dir = f"{base}/{split}/images"
    lbl_dir = f"{base}/{split}/labels"
    if os.path.exists(img_dir):
        for f in os.listdir(img_dir):
            shutil.copy(os.path.join(img_dir, f), os.path.join(combined_img, f))
    if os.path.exists(lbl_dir):
        for f in os.listdir(lbl_dir):
            shutil.copy(os.path.join(lbl_dir, f), os.path.join(combined_lbl, f))

print("Total images:", len(os.listdir(combined_img)))
print("Total labels:", len(os.listdir(combined_lbl)))

import os, shutil, random

base = "Lozy-Merged--1"
combined_img = f"{base}/all_images"
combined_lbl = f"{base}/all_labels"

all_files = [f for f in os.listdir(combined_img)]
random.seed(42)
random.shuffle(all_files)

n = len(all_files)
n_train = int(n * 0.8)
n_valid = int(n * 0.1)

splits = {
    "train": all_files[:n_train],
    "valid": all_files[n_train:n_train + n_valid],
    "test": all_files[n_train + n_valid:]
}

for split in ["train", "valid", "test"]:
    img_out = f"{base}/{split}/images"
    lbl_out = f"{base}/{split}/labels"
    shutil.rmtree(img_out, ignore_errors=True)
    shutil.rmtree(lbl_out, ignore_errors=True)
    os.makedirs(img_out, exist_ok=True)
    os.makedirs(lbl_out, exist_ok=True)

    for img_file in splits[split]:
        label_file = os.path.splitext(img_file)[0] + ".txt"
        shutil.copy(os.path.join(combined_img, img_file), os.path.join(img_out, img_file))
        label_path = os.path.join(combined_lbl, label_file)
        if os.path.exists(label_path):
            shutil.copy(label_path, os.path.join(lbl_out, label_file))

for split in ["train", "valid", "test"]:
    print(split, ":", len(os.listdir(f"{base}/{split}/images")), "images")

print(open("Lozy-Merged--1/data.yaml").read())

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.train(
    data="Lozy-Merged--1/data.yaml",
    epochs=50,
    imgsz=416,
    batch=16,
    patience=15,
    project="id_detection",
    name="yolov8n_run1"
)

import glob, random
from ultralytics import YOLO

model = YOLO("/content/runs/detect/id_detection/yolov8n_run1/weights/best.pt")

test_images = glob.glob("Lozy-Merged--1/test/images/*")
random_img_path = random.choice(test_images)
print(random_img_path)

result = model.predict(random_img_path, save=True, conf=0.5)

from PIL import Image
Image.open(result[0].save_dir + "/" + random_img_path.split("/")[-1])

import matplotlib.pyplot as plt
from PIL import Image

def show_each_class_separately(image_path, conf=0.5):
    img = Image.open(image_path)
    results = model.predict(image_path, conf=conf, verbose=False)
    boxes = results[0].boxes
    names = results[0].names

    n = len(boxes)
    if n == 0:
        print("There is no face")
        return

    fig, axes = plt.subplots(1, n, figsize=(4 * n, 4))
    if n == 1:
        axes = [axes]

    for i, box in enumerate(boxes):
        cls_id = int(box.cls[0])
        cls_name = names[cls_id]
        conf_val = float(box.conf[0])
        x1, y1, x2, y2 = map(int, box.xyxy[0].tolist())
        crop = img.crop((x1, y1, x2, y2))

        axes[i].imshow(crop)
        axes[i].set_title(f"{cls_name}\n{conf_val:.2f}")
        axes[i].axis("off")

    plt.tight_layout()
    plt.show()

show_each_class_separately(random_img_path)

from google.colab import files
from ultralytics import YOLO
from PIL import Image
import matplotlib.pyplot as plt
import shutil

uploaded = files.upload()
original_name = list(uploaded.keys())[0]
image_path = "uploaded_id.jpg"
shutil.copy(original_name, image_path)
print("Uploaded and renamed to:", image_path)

model = YOLO("/content/runs/detect/id_detection/yolov8n_run1/weights/best.pt")

result = model.predict(image_path, save=True, conf=0.15)
img_with_boxes = Image.open(result[0].save_dir + "/" + image_path)
display(img_with_boxes)

img = Image.open(image_path)
results = model.predict(image_path, conf=0.15, verbose=False)
boxes = results[0].boxes
names = results[0].names

best_boxes = {}
for box in boxes:
    cls_id = int(box.cls[0])
    cls_name = names[cls_id]
    conf_val = float(box.conf[0])
    if cls_name not in best_boxes or conf_val > best_boxes[cls_name][1]:
        best_boxes[cls_name] = (box, conf_val)

n = len(best_boxes)
if n == 0:
    print("No fields detected in this image")
else:
    fig, axes = plt.subplots(1, n, figsize=(4 * n, 4))
    if n == 1:
        axes = [axes]

    for i, (cls_name, (box, conf_val)) in enumerate(best_boxes.items()):
        x1, y1, x2, y2 = map(int, box.xyxy[0].tolist())
        crop = img.crop((x1, y1, x2, y2))
        axes[i].imshow(crop)
        axes[i].set_title(f"{cls_name} {conf_val:.2f}")
        axes[i].axis("off")

    plt.tight_layout()
    plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile extract_face_from_id.py
# 
# from ultralytics import YOLO
# from PIL import Image
# 
# model = YOLO("best.pt")
# 
# def extract_face_from_id(image_path, conf=0.5):
#     results = model.predict(image_path, conf=conf, verbose=False)
#     boxes = results[0].boxes
#     names = results[0].names
# 
#     best_conf = -1
#     face_box = None
#     for box in boxes:
#         cls_id = int(box.cls[0])
#         if names[cls_id] == "Face":
#             conf_val = float(box.conf[0])
#             if conf_val > best_conf:
#                 best_conf = conf_val
#                 face_box = box.xyxy[0].tolist()
# 
#     if face_box is None:
#         return None
# 
#     img = Image.open(image_path)
#     x1, y1, x2, y2 = map(int, face_box)
#     return img.crop((x1, y1, x2, y2))
